### ISSUE TITLE
Request: Add *.pyc to .gitignore

### ISSUE THREAD

**Issue by ameyp** [tkf/python-epc#6]
Generated .pyc files show up as "Untracked files", which is a minor annoyance.

**Comment by tkf** [comment]
I use global gitignore to ignore pyc.  I think standard compiled files and environment specific files like `*~` and `#*#` generated by editor should be ignored by the global gitignore file.  See: https://help.github.com/articles/ignoring-files

That said, if you send a PR to ignore pyc files I have no reason to reject it.

**Comment by ameyp** [comment]
Thanks, I've sent a pull request for this. https://github.com/tkf/python-epc/pull/7

**Comment by tkf** [comment]
Pulled #7. Thanks.
